### ISSUE TITLE
Missing weapons from Impulse 101

### ISSUE THREAD

**Issue by epicplayer40** [RoyaleNoir/manwich-oddyssey-src#1]
The following weapons will not be given to the player when using impulse 101:
weapon_katana
weapon_uzi
weapon_mp5
weapon_p90
weapon_garand
weapon_cguard
weapon_immolator
weapon_flaregun

**Comment by epicplayer40** [comment]
Update: Sniper/Flare ammo is not given to the player either.

**Comment by RoyaleNoir** [comment]
Added those to player.cpp
