### ISSUE TITLE
Wasteland/Combine Conscripts Crash the Game with Allies Taking Damage Nearby

### ISSUE THREAD

**Issue by epicplayer40** [RoyaleNoir/manwich-oddyssey-src#11]
If a tan soldier and wasteland Conscript are close to each other and you shoot at them, the game will crash.
This will also happen if a Combine Conscript is near a Combine ally such as a Cremator.
I am not sure exactly what can cause this issue but it seems to do with Conscript variants being close to their allies and taking damage.

**Comment by RoyaleNoir** [comment]
this bug is causing me physical pain

**Comment by epicplayer40** [comment]
Shhh calm down you're fine

**Comment by epicplayer40** [comment]
This issue is fixed and should be closed.
