### ISSUE TITLE
Gonome issues and crashes

### ISSUE THREAD

**Issue by epicplayer40** [RoyaleNoir/manwich-oddyssey-src#4]
The gonome does not precache certain sounds, particles and entities which is causing the game to have errors:

SV_StartSound: npc/zombie/claw_strike1.wav not precached (0)
Client: Missing precache for particle system "blood_impact_zombie_01"!
Client: Missing precache for particle system "blood_impact_zombie_01"!

These fix themselves if a npc_zombie is also spawned however this can be easily fixed in the code.

The game also crashes when the gonome uses its spit attack, but I suspect this is because the thrown spit entity does not exist or isn't precached.

**Comment by epicplayer40** [comment]
Update: the crashing from the spit attack was related to a missing material which has been fixed.

**Comment by Apollyon094** [comment]
edward

**Comment by RoyaleNoir** [comment]
I tried to fix it, but i am unable to test due to missing assets
