### ISSUE TITLE
Bullsquid Spit Attack Crashes the Game

### ISSUE THREAD

**Issue by epicplayer40** [RoyaleNoir/manwich-oddyssey-src#9]
When a bullsquid is spitting, the creation of the spit entity causes the game to crash. I suspect this is caused by the "squidspit" entity being defined twice in the bullsquid and gonome code.

**Comment by epicplayer40** [comment]
squidspit is ALSO defined a third time in npc_ashdude.cpp.

**Comment by RoyaleNoir** [comment]
should be fixed
